<?php

namespace RedJasmine\Wallet\Application\Services\Wallet\Commands;


use RedJasmine\Support\Application\Commands\CommandContext;
use RedJasmine\Support\Application\Commands\CreateCommandHandler;
use RedJasmine\Support\Application\HandleContext;
use RedJasmine\Wallet\Application\Services\Wallet\WalletApplicationService;
use RedJasmine\Wallet\Exceptions\WalletException;
use RedJasmine\Wallet\Facades\Wallet;

/**
 * @property WalletApplicationService $service
 */
class WalletCreateCommandHandler extends CreateCommandHandler
{

    protected WalletApplicationService $service;

    /**
     * @param  CommandContext  $context
     *
     * @return void
     * @throws WalletException
     */
    protected function validate(CommandContext $context) : void
    {
        parent::validate($context);
        /**
         * @var WalletCreateCommand $command
         */
        $command = $context->getCommand();
        $this->service->walletService->walletValidate($command->type, $command->owner);
    }

    /**
     * 填充转换数据
     *
     * @param  HandleContext  $context
     *
     * @return void
     * @throws WalletException
     */
    protected function fill(HandleContext $context) : void
    {
        parent::fill($context); // TODO: Change the autogenerated stub

        /**
         * @var WalletCreateCommand $command
         */
        $command = $context->getCommand();
        /**
         * @var Wallet $model
         */
        $model = $context->getModel();

        $walletConfig = $this->service->walletService->getWalletConfig($command->type);

        $model->currency = $walletConfig->currency;

    }


}