@startuml generate_poster_sequence

title 生成邀请海报时序图 / Generate Invitation Poster Sequence

actor 邀请人 as Inviter
participant "海报应用服务" as PosterApp
participant "海报模板仓库" as TemplateRepo
participant "邀请码仓库" as CodeRepo
participant "二维码生成器" as QRGenerator
participant "图片渲染器" as ImageRenderer
participant "文件存储服务" as FileStorage
participant "缓存服务" as Cache

Inviter -> PosterApp: 请求生成海报
activate PosterApp

PosterApp -> TemplateRepo: 获取海报模板
activate TemplateRepo
TemplateRepo --> PosterApp: 模板数据
deactivate TemplateRepo

PosterApp -> CodeRepo: 获取邀请码信息
activate CodeRepo
CodeRepo --> PosterApp: 邀请码信息
deactivate CodeRepo

PosterApp -> QRGenerator: 生成邀请二维码
activate QRGenerator
QRGenerator --> PosterApp: 二维码图片
deactivate QRGenerator

PosterApp -> ImageRenderer: 渲染海报
activate ImageRenderer

ImageRenderer -> ImageRenderer: 加载模板资源
ImageRenderer -> ImageRenderer: 渲染文字内容
ImageRenderer -> ImageRenderer: 嵌入二维码
ImageRenderer -> ImageRenderer: 应用样式效果

ImageRenderer --> PosterApp: 海报图片数据
deactivate ImageRenderer

PosterApp -> FileStorage: 保存海报文件
activate FileStorage
FileStorage --> PosterApp: 文件访问链接
deactivate FileStorage

PosterApp -> Cache: 缓存海报信息
activate Cache
Cache --> PosterApp: 缓存成功
deactivate Cache

PosterApp --> Inviter: 返回海报下载链接
deactivate PosterApp

note right of Inviter
  邀请人可以下载海报
  或直接分享到社交平台
end note

@enduml 