<?php

namespace RedJasmine\Interaction\Domain\Types;

use RedJasmine\Interaction\Domain\Data\InteractionData;

class LikeInteractionType extends BaseInteractionType
{
    public function validate(InteractionData $data)
    {
        parent::validate($data); // TODO: Change the autogenerated stub
    }

}