<?php

namespace RedJasmine\Interaction\Infrastructure\ReadRepositories\Mysql;

use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use RedJasmine\Interaction\Domain\Facades\InteractionType;
use RedJasmine\Interaction\Domain\Models\InteractionRecord;
use RedJasmine\Interaction\Domain\Repositories\InteractionRecordReadRepositoryInterface;
use RedJasmine\Support\Domain\Data\Queries\Query;
use RedJasmine\Support\Infrastructure\ReadRepositories\QueryBuilderReadRepository;
use Spatie\QueryBuilder\AllowedFilter;

class InteractionRecordReadRepository extends QueryBuilderReadRepository
    implements InteractionRecordReadRepositoryInterface
{
    protected static string $modelClass = InteractionRecord::class;


    public function modelQuery(?Query $query = null) : Builder
    {

        $interactionType    = InteractionType::create($query->interactionType);
        static::$modelClass = $interactionType->getModelClass();
        return parent::modelQuery();
    }

    protected function buildRequest(array $requestQuery = []) : Request
    {
        $requestQuery = array_merge($requestQuery, $requestQuery['other'] ?? []);
        unset($requestQuery['other']);
        return parent::buildRequest($requestQuery); // TODO: Change the autogenerated stub
    }


    public function allowedFilters(?Query $query = null) : array
    {
        $interactionType = InteractionType::create($query->interactionType);

        return [
            ...$interactionType->allowedFields(),
            AllowedFilter::exact('resource_type'),
            AllowedFilter::exact('resource_id'),
            AllowedFilter::exact('interaction_type'),
            AllowedFilter::exact('user_id'),
            AllowedFilter::exact('user_type'),
        ];
    }
}