<?php

namespace RedJasmine\FilamentCore\Filters;

class DateRangeFilter extends \Malzariey\FilamentDaterangepickerFilter\Filters\DateRangeFilter
{

    protected function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->withIndicator()
             ->alwaysShowCalendar()
             ->timePickerSecond()
             ->displayFormat('YYYY/MM/DD')
             ->format('Y/m/d')
             ->timePicker24()
             ->icon('heroicon-o-backspace')
             ->linkedCalendars()
             ->autoApply();
    }

}
