<?php

namespace RedJasmine\FilamentCore\Filters;

use Filament\Tables\Filters\Filter;
use Filament\Forms;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Str;

class InputFilter extends Filter
{

    protected function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->form([
                        Forms\Components\TextInput::make('value')->label(fn() => $this->evaluate($this->inputLabel))

                    ]);
        // TODO 是否允许多个
        $this->query(function (Builder $query, array $data) : Builder {
            return $query->when(Str::replace([ ',', ',', ' ' ], ',', $data['value'] ?? ''),
                fn(Builder $query, $value) : Builder => $query->whereIn($this->getName(), explode(',', $value)));
        });
    }

    protected string|Htmlable|Closure|null $inputLabel = null;

    public function inputLabel(string|Htmlable|Closure|null $label) : static
    {

        $this->inputLabel = $label;

        return $this;
    }

}
