<?php

namespace RedJasmine\Wallet\Infrastructure\Repositories\Eloquent;

use RedJasmine\Support\Infrastructure\Repositories\Eloquent\EloquentRepository;
use RedJasmine\Wallet\Domain\Models\WalletWithdrawal;
use RedJasmine\Wallet\Domain\Repositories\WalletWithdrawalRepositoryInterface;


class WalletWithdrawalRepository extends EloquentRepository implements WalletWithdrawalRepositoryInterface
{


    protected static string $eloquentModelClass = WalletWithdrawal::class;

    public function findByNo(string $no) : WalletWithdrawal
    {
        return static::$eloquentModelClass::uniqueNo($no)->firstOrFail();
    }

    /**
     * @param  string  $no
     *
     * @return WalletWithdrawal
     */
    public function findByNoLock(string $no) : WalletWithdrawal
    {
        return parent::findByNoLock($no); // TODO: Change the autogenerated stub
    }


}